<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSp697fg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSp697fg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSp697fg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSp697fg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSp697fg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sp697fg',
    'container.build_id' => '83a9c2c8',
    'container.build_time' => 1637822703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSp697fg');
